### ISSUE TITLE
Weekly Meetupについての文言を修正する

### ISSUE THREAD

**Issue by hanachin** [okinawarb/okinawarb.github.io#2]
https://github.com/okinawarb/okinawarb.github.io/pull/1 の修正が https://github.com/okinawarb/okinawarb.github.io/commit/0d84c7616c0455579e185d1a1ae12ed2501bc350 で消えたため

**Comment by yasulab** [comment]
Oops, 修正します :sweat:

**Comment by yasulab** [comment]
Fixed this issue by https://github.com/okinawarb/okinawarb.github.io/commit/db177a14430c386be0029a02495a70f09c4b2d8b
